apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: _CI_GROUP_NAME_-APP_NAME-PACKAGE_NAME
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: _CI_GROUP_NAME_-APP_NAME-PACKAGE_NAME
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
---

