---
kind: Service
apiVersion: v1
metadata:
  name: _CI_GROUP_NAME_-APP_NAME-PACKAGE_NAME
  namespace: web-app
spec:
  selector:
    app: _CI_GROUP_NAME_-APP_NAME-PACKAGE_NAME
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: APP_NAME
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: _CI_GROUP_NAME_-APP_NAME-PACKAGE_NAME
  namespace: web-app
  annotations:
    kubernetes.io/ingress.class: 'kong'
    konghq.com/override: kong-ingress
    konghq.com/preserve-host: 'true'
    konghq.com/protocols: https
spec:
  tls:
    - hosts:
        - appv3.ahamove.com
      secretName: ahamove
  rules:
    - host: appv3.ahamove.com
      http:
        paths:
          - path: '/'
            pathType: Prefix
            backend:
              service:
                name: _CI_GROUP_NAME_-APP_NAME-PACKAGE_NAME
                port:
                  number: 80
